import 'package:edutrack_app/features/communication/data/models/message.dart';

/// The prototype's own log rows, as models.
const absenceSms = Message(
  id: 1,
  schoolId: 1,
  event: 'attendance.absent',
  eventLabel: 'Marked absent',
  category: MessageCategory.attendance,
  channel: MessageChannel.sms,
  recipientName: 'Raj Kumar',
  recipientMobile: '+91 9876543210',
  studentId: 7,
  studentName: 'Arjun Kumar',
  subject: null,
  body: 'Arjun Kumar was marked ABSENT on 16 Sep 2026.',
  status: MessageStatus.sent,
  provider: 'log',
  providerLabel: 'Demo Gateway',
  failureReason: null,
  sentAt: '2026-09-16T08:42:00.000000Z',
  readAt: null,
  createdAt: '2026-09-16T08:42:00.000000Z',
  createdAtLabel: '8:42 AM',
  sentAtLabel: null,
  createdOnLabel: '16 Sep 2026',
);

const boardingSms = Message(
  id: 2,
  schoolId: 1,
  event: 'transport.boarded',
  eventLabel: 'Boarded the bus',
  category: MessageCategory.transport,
  channel: MessageChannel.sms,
  recipientName: 'Neha Mehta',
  recipientMobile: '+91 9812345678',
  studentId: 8,
  studentName: 'Aarav Mehta',
  subject: null,
  body: 'Aarav Mehta boarded Bus 04 at Lake View at 7:42 AM.',
  status: MessageStatus.sent,
  provider: 'log',
  providerLabel: 'Demo Gateway',
  failureReason: null,
  sentAt: '2026-09-16T07:42:00.000000Z',
  readAt: null,
  createdAt: '2026-09-16T07:42:00.000000Z',
  createdAtLabel: '7:42 AM',
  sentAtLabel: null,
  createdOnLabel: '16 Sep 2026',
);

/// One the gateway rejected, so the log offers to send it again.
const failedSms = Message(
  id: 3,
  schoolId: 1,
  event: 'attendance.absent',
  eventLabel: 'Marked absent',
  category: MessageCategory.attendance,
  channel: MessageChannel.sms,
  recipientName: 'Rohit Singh',
  recipientMobile: '+91 9800000000',
  studentId: 9,
  studentName: 'Meera Singh',
  subject: null,
  body: 'Meera Singh was marked ABSENT on 16 Sep 2026.',
  status: MessageStatus.failed,
  provider: 'log',
  providerLabel: 'Demo Gateway',
  failureReason: 'The gateway rejected the number.',
  sentAt: null,
  readAt: null,
  createdAt: '2026-09-16T08:45:00.000000Z',
  createdAtLabel: '8:45 AM',
  sentAtLabel: null,
  createdOnLabel: '16 Sep 2026',
);

/// One the school wanted to send but had no number for.
const skippedSms = Message(
  id: 4,
  schoolId: 1,
  event: 'attendance.absent',
  eventLabel: 'Marked absent',
  category: MessageCategory.attendance,
  channel: MessageChannel.sms,
  recipientName: 'Anita Rao',
  recipientMobile: null,
  studentId: 10,
  studentName: 'Kiran Rao',
  subject: null,
  body: 'Kiran Rao was marked ABSENT on 16 Sep 2026.',
  status: MessageStatus.skipped,
  provider: 'log',
  providerLabel: 'Demo Gateway',
  failureReason: 'No mobile number on record.',
  sentAt: null,
  readAt: null,
  createdAt: '2026-09-16T08:46:00.000000Z',
  createdAtLabel: '8:46 AM',
  sentAtLabel: null,
  createdOnLabel: '16 Sep 2026',
);

const leaveInApp = Message(
  id: 5,
  schoolId: 1,
  event: 'leave.approved',
  eventLabel: 'Leave approved',
  category: MessageCategory.leave,
  channel: MessageChannel.inApp,
  recipientName: 'Priya Sharma',
  recipientMobile: null,
  studentId: null,
  studentName: null,
  subject: null,
  body: 'Your casual leave from 21 Sep 2026 to 22 Sep 2026 has been approved.',
  status: MessageStatus.sent,
  provider: null,
  providerLabel: null,
  failureReason: null,
  sentAt: '2026-09-16T09:00:00.000000Z',
  readAt: null,
  createdAt: '2026-09-16T09:00:00.000000Z',
  createdAtLabel: '9:00 AM',
  sentAtLabel: null,
  createdOnLabel: '16 Sep 2026',
);

const readInApp = Message(
  id: 6,
  schoolId: 1,
  event: 'leave.rejected',
  eventLabel: 'Leave rejected',
  category: MessageCategory.leave,
  channel: MessageChannel.inApp,
  recipientName: 'Priya Sharma',
  recipientMobile: null,
  studentId: null,
  studentName: null,
  subject: null,
  body: 'Your medical leave from 01 Sep 2026 to 02 Sep 2026 was not approved.',
  status: MessageStatus.sent,
  provider: null,
  providerLabel: null,
  failureReason: null,
  sentAt: '2026-09-15T09:00:00.000000Z',
  readAt: '2026-09-15T10:00:00.000000Z',
  createdAt: '2026-09-15T09:00:00.000000Z',
  createdAtLabel: '9:00 AM',
  sentAtLabel: null,
  createdOnLabel: '15 Sep 2026',
);

/// An announcement's in-app copy, which carries its title as the subject.
const announcementInApp = Message(
  id: 7,
  schoolId: 1,
  event: 'announcement.published',
  eventLabel: 'Announcement',
  category: MessageCategory.announcement,
  channel: MessageChannel.inApp,
  recipientName: 'Priya Sharma',
  recipientMobile: null,
  studentId: null,
  studentName: null,
  subject: 'Sports day moved',
  body: 'Sunrise Public School: Sports day moved - The sports day is now on Friday.',
  status: MessageStatus.sent,
  provider: null,
  providerLabel: null,
  failureReason: null,
  sentAt: '2026-09-16T09:30:00.000000Z',
  readAt: null,
  createdAt: '2026-09-16T09:30:00.000000Z',
  createdAtLabel: '9:30 AM',
  sentAtLabel: null,
  createdOnLabel: '16 Sep 2026',
);

const absentTemplate = MessageTemplate(
  event: 'attendance.absent',
  eventLabel: 'Marked absent',
  category: MessageCategory.attendance,
  channels: [MessageChannel.sms],
  body: '{student_name} was marked ABSENT on {date}.',
  defaultBody: '{student_name} was marked ABSENT on {date}.',
  isCustom: false,
  tokens: ['student_name', 'class_name', 'date', 'school_name', 'guardian_name'],
  updatedByName: null,
);

const boardedTemplate = MessageTemplate(
  event: 'transport.boarded',
  eventLabel: 'Boarded the bus',
  category: MessageCategory.transport,
  channels: [MessageChannel.sms],
  body: 'Reworded: {student_name} is on {vehicle_name}.',
  defaultBody: '{student_name} boarded {vehicle_name} at {stop_name} at {time}.',
  isCustom: true,
  tokens: ['student_name', 'stop_name', 'vehicle_name', 'route_name', 'time', 'date', 'school_name', 'guardian_name'],
  updatedByName: 'Anita Sharma',
);

const defaultTemplates = [absentTemplate, boardedTemplate];

const defaultSettings = CommunicationSettings(
  schoolId: 1,
  smsEnabled: true,
  attendanceAlerts: AttendanceAlertMode.absentOnly,
  transportAlertsEnabled: true,
  leaveAlertsEnabled: true,
  provider: 'log',
  providerLabel: 'Demo Gateway',
  senderId: null,
  availableProviders: [SmsProviderOption(value: 'log', label: 'Demo Gateway')],
  isSaved: false,
);

/// Copies a message with a couple of fields changed - the model is
/// deliberately immutable, and only the fakes need this.
Message messageAs(Message source, {MessageStatus? status, Object? failureReason = _keep, String? readAt}) {
  return Message(
    id: source.id,
    schoolId: source.schoolId,
    event: source.event,
    eventLabel: source.eventLabel,
    category: source.category,
    channel: source.channel,
    recipientName: source.recipientName,
    recipientMobile: source.recipientMobile,
    studentId: source.studentId,
    studentName: source.studentName,
    subject: source.subject,
    body: source.body,
    status: status ?? source.status,
    provider: source.provider,
    providerLabel: source.providerLabel,
    failureReason: failureReason == _keep ? source.failureReason : failureReason as String?,
    sentAt: source.sentAt,
    readAt: readAt ?? source.readAt,
    createdAt: source.createdAt,
    createdAtLabel: source.createdAtLabel,
    createdOnLabel: source.createdOnLabel,
    sentAtLabel: source.sentAtLabel,
  );
}

MessageTemplate templateAs(MessageTemplate source, {String? body, bool? isCustom}) {
  return MessageTemplate(
    event: source.event,
    eventLabel: source.eventLabel,
    category: source.category,
    channels: source.channels,
    body: body ?? source.body,
    defaultBody: source.defaultBody,
    isCustom: isCustom ?? source.isCustom,
    tokens: source.tokens,
    updatedByName: source.updatedByName,
  );
}

const _keep = Object();
