"""The routes this backend serves.

Everything hangs under /api/v1/ because that is what the Flutter apps already
call. The prefix is not a style choice; it is part of the contract.

M8 serves auth and students. The other 143 endpoints arrive module by module
from M9, each one landing only when its contract tests pass
(../contract/README.md). Until then this backend answers 404 for them, which
is why it runs alongside Laravel rather than instead of it.

Paths are spelled out one at a time rather than generated by a DRF router.
A router would invent its own URLs - trailing slashes, a `-detail` suffix,
`/students/1/activate/` - and every one of those is a URL the Flutter client
does not call.
"""

from django.urls import path

from school.views import (
    academic_config,
    academic_years,
    attendance,
    auth,
    classes,
    imports,
    payments,
    schools,
    staff,
    students,
    timezones,
    users,
)

urlpatterns = [
    # -- academic years ----------------------------------------------------
    path("api/v1/academic-years", academic_years.collection),
    path("api/v1/academic-years/<int:year_id>", academic_years.detail),
    path("api/v1/academic-years/<int:year_id>/set-current", academic_years.set_current),
    # -- classes, sections, periods and holidays ---------------------------
    path("api/v1/classes", classes.classes),
    path("api/v1/classes/<int:class_id>", classes.school_class),
    path("api/v1/classes/<int:class_id>/sections", classes.add_section),
    path("api/v1/sections/<int:section_id>", classes.section),
    path("api/v1/periods", classes.periods),
    path("api/v1/periods/<int:period_id>", classes.period),
    path("api/v1/holidays", classes.holidays),
    path("api/v1/holidays/<int:holiday_id>", classes.holiday),
    # -- departments and subjects ------------------------------------------
    path("api/v1/departments", academic_config.departments),
    path("api/v1/departments/<int:department_id>", academic_config.department),
    path("api/v1/subjects", academic_config.subjects),
    path("api/v1/subjects/<int:subject_id>", academic_config.subject),
    # -- student attendance ------------------------------------------------
    # `register` before the collection so the word is not read as a filter.
    path("api/v1/attendance/register", attendance.register),
    path("api/v1/attendance", attendance.collection),
    # -- auth --------------------------------------------------------------
    path("api/v1/auth/login", auth.login),
    path("api/v1/auth/logout", auth.logout),
    path("api/v1/auth/change-password", auth.change_password),
    path("api/v1/me", auth.me),
    # -- payments ----------------------------------------------------------
    # `summary` before `<int:payment_id>` so the word is not read as an id.
    path("api/v1/payments", payments.collection),
    path("api/v1/payments/summary", payments.summary),
    path("api/v1/payments/<int:payment_id>", payments.detail),
    path("api/v1/payments/<int:payment_id>/receipt", payments.receipt),
    # -- schools -----------------------------------------------------------
    # No DELETE, and not by omission: erasing a school's records is not
    # something a school management system should offer.
    path("api/v1/schools", schools.collection),
    path("api/v1/schools/<int:school_id>", schools.detail),
    path("api/v1/schools/<int:school_id>/activate", schools.activate),
    path("api/v1/schools/<int:school_id>/deactivate", schools.deactivate),
    path("api/v1/timezones", timezones.index),
    # -- users -------------------------------------------------------------
    path("api/v1/users", users.collection),
    path("api/v1/users/<int:user_id>", users.detail),
    path("api/v1/users/<int:user_id>/activate", users.activate),
    path("api/v1/users/<int:user_id>/deactivate", users.deactivate),
    # -- teachers and staff ------------------------------------------------
    # No delete: somebody who has left is deactivated through /users, which
    # keeps their attendance, their leave and last year's timetable intact.
    path("api/v1/staff", staff.collection),
    path("api/v1/staff/<int:profile_id>", staff.detail),
    # -- students ----------------------------------------------------------
    path("api/v1/students", students.collection),
    path("api/v1/students/<int:student_id>", students.detail),
    path("api/v1/students/<int:student_id>/activate", students.activate),
    path("api/v1/students/<int:student_id>/deactivate", students.deactivate),
    # -- bulk upload -------------------------------------------------------
    # The kind of record is a path segment, so one pair of endpoints serves
    # every importer. M8 registers `students`; the rest arrive with their
    # modules, and anything else is a 404.
    path("api/v1/imports/<str:kind>", imports.store),
    path("api/v1/imports/<str:kind>/template", imports.template),
]

# A URL matching no route above never reaches DRF, so it would answer Django's
# HTML page - which the Flutter client reads as a parse failure rather than as
# a 404. These keep the error envelope true for every path, including the 143
# endpoints this backend has not ported yet.
#
# Django only uses them when DEBUG is off; with DEBUG on it shows its own
# route-listing page instead, which is the right trade for a developer and the
# reason the test for this pins DEBUG=False.
handler404 = "school.errors.page_not_found"
handler500 = "school.errors.server_error"
